version: '3.4'
services:
  pyats:
    image: pyats
    ports:
             - "8005:8005"
    volumes:
             - ./pyats:/pyats/tests:z
             - ./pyats.conf:/etc/pyats.conf
             - ./archive:/root/.pyats/archive:z
    tty: true
